[[language]]
name = "nix"
language-servers = [ "nil", "nixd" ]

[language-server.nixd]
command = "nixd"

[language-server.nixd.config.nixd]
nixpkgs = { expr = "import <nixpkgs> {};" }
formatting = { command = [ "nixfmt" ] }

[language-server.nixd.config.nixd.options]

# for l4pt2 host
nixos = { expr = "(builtins.getFlake (builtins.toString ./.)).nixosConfigurations.l4pt2.options" }

# # for h0t2 host
# nixos = { expr = "(builtins.getFlake (builtins.toString ./.)).nixosConfigurations.h0t2.options" }
